context:
  version: "0.8.0"

package:
  name: air
  version: ${{ version }}

source:
  url: https://github.com/posit-dev/air/archive/refs/tags/${{ version }}.tar.gz
  sha256: fbce4a9698c756dc4d65eb6cb845fcdd8bca952f25b988711037b6ff9b82a99c

build:
  script:
    - if: win
      then:
        - set CARGO_HOME=C:\cargo
    - cargo install --path crates/air --root ${{ PREFIX }} --no-track
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}

tests:
  - script:
    - air --help

about:
  homepage: https://github.com/posit-dev/air
  license: MIT
  summary: Fast and opinionated formatter for R code
  description: |
    Air is a fast and opinionated formatter for R code that helps maintain
    consistent code style and formatting across R projects.
